### ISSUE TITLE
Update main README.md

### ISSUE THREAD

**Issue by Pritish-Sinha** [Pritish-Sinha/Machine-Leaning-Project#8]
Please update main README.md to list new projects and tutorials.

**Comment by Anirban-Chand** [comment]
Hi,
I can do this. Please assign me this @Pritish-Sinha

**Comment by DakshVarshney1409** [comment]
I would like to contribute. Please assign it to me @Pritish-Sinha

**Comment by durgesh-4526** [comment]
@Pritish-Sinha Kindly Check #22

**Comment by advik-student-dev** [comment]
can i upload my ml project. learned and made from youtube

**Comment by advik-student-dev** [comment]
not great at ml
followed a tutorial a while back, may still have the file
can the file be .py?

**Comment by Pritish-Sinha** [comment]
Yeah anything that contributes in ml field.
